#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt35523_TIANMA_qxga_dsi_vdo_truly.o lcm_nt35523_TIANMA_qxga_dsi_vdo_truly.o lp8557.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
