#
# Makefile for the touchscreen drivers.
#
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_Z500M_ATMEL_MXT_1666T2)	+= Z500M_atmel_mxt1666t2.o
